pipeline {
agent any
    stages {
        stage('Build') {
            steps {
            echo 'Build Stage'
                script {
                customImage = docker.build("autoaudit-backend:${env.BUILD_ID}", 
                "-f backend-api/Dockerfile . ")
                }
            } 
        }       
        stage('Test') {
            steps {
            echo 'Test Stage'
            dir('backend-api') {
                bat 'uv run pytest --junitxml=results.xml'
            }
        }
    }
    
        stage('Code Quality') {
            steps {
            echo 'Code Quality'
            }
        }
        stage('Security') {
            steps {
            echo 'Security Stage'
            }
        }
        stage('Deploy') {
            steps {
            echo 'Deploy Stage'
            }
        }
        stage('Release') {
            steps {
            echo 'Release Stage'
            }
        }
        stage('Monitoring') {
            steps {
            echo 'Monitoring Stage'
            }
        }
    }
    post {
        always {
            junit 'backend-api/results.xml'
            }
        }
}